### ISSUE TITLE
Conflict with the same port

### ISSUE THREAD

**Issue by tjedrak** [Xilonz/trellis-nixstats#1]
Nignx and phpfpm have the same 8080 port that causes conflict.

Feb 24 17:33:482020/02/24 16:33:40 [warn] 20082#20082: conflicting server name "localhost" on 0.0.0.0:8080, ignored
```
nixstats_database_enabled: true #(optional)
nixstats_nginx_enabled: true #(optional)
nixstats_phpfpm_enabled: true #(optional)
```

**Comment by Xilonz** [comment]
Hi! Thanks for reporting and trying out trellis-nixstats. Its been a while since I worked on this so I'll have take a look soon™.

**Comment by tjedrak** [comment]
Thanks @Xilonz

**Comment by Xilonz** [comment]
@tjedrak The issue should be resolved

**Comment by tjedrak** [comment]
It is, thank you @Xilonz
